org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.4
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

spartan_weaponry_version=3.1.0-beta-1
spartan_toolkit_version=1.3.0
spartan_toolkit_limit = 2.0.0

simpleores_version=6.0.0.3
simplecorelib_version=6.0.1.2
bucketlib_version=2.3.0.0

## Mod Properties

mod_id=spartansimpleores
mod_name=Spartan Weaponry: SimpleOres
mod_license=GPL-3.0
mod_version=2.1.0
mod_issue_tracker=https://github.com/KreloX/SpartanSimpleOres/issues
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/spartan-weaponry-simpleores
mod_credits=
mod_group_id=krelox.spartansimpleores
mod_authors=KreloX
mod_description=Addon mod for Spartan Weaponry that adds compatibility with SimpleOres.
pack_format_number=9